name: Python Lint and Security lib

on:
  push:
    branches: [ "*" ]

jobs:

  lint_tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    name: Linting
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Install dependencies
        run: |
          uv venv
          uv pip install ruff bandit

      - name: Run AI_LIB Ruff
        run: |
          cd src
          uv run ruff check ./sdg_core_lib
          uv run ruff format --check ./sdg_core_lib

      - name: Run AI_LIB bandit
        run: |
          cd src
          uv run bandit -c bandit.yaml -r ./sdg_core_lib
